# Generated by Django 3.1.2 on 2020-10-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('pizza_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TapTheTableResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=200)),
                ('vegan_pizza_type', models.CharField(max_length=200)),
                ('menu_description', models.TextField(blank=True)),
                ('facebook_page', models.CharField(blank=True, max_length=200)),
                ('online_ordering_link', models.CharField(blank=True, max_length=200)),
                ('pizza_photo', models.ImageField(blank=True, upload_to='images/')),
                ('is_subscriber', models.BooleanField(default=False, help_text='Indicates whether this pizzeria subscribes to PMQ Magazine', verbose_name='Subscribes to PMQ?')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
