# Generated by Django 3.1.2 on 2020-10-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tapthetableresponse',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tapthetableresponse',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Indicates whether this listing has been approved for display'),
        ),
        migrations.AddField(
            model_name='tapthetableresponse',
            name='state',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='tapthetableresponse',
            name='street_address1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Street Address 1'),
        ),
        migrations.AddField(
            model_name='tapthetableresponse',
            name='street_address2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Street Address 2'),
        ),
        migrations.AddField(
            model_name='tapthetableresponse',
            name='zip_code',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
